---
# Source: omegared/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "omegared-nginx-svc"
  namespace: myomega
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    app.kubernetes.io/name: "omegared-nginx"
---
# Source: omegared/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "omegared-nginx-dep"
spec:
  replicas: 1
  selector:
    matchLabels: 
      app.kubernetes.io/name: "omegared-nginx"
  template:
    metadata:
    spec:
      containers:
        - name: omegared
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
