apiVersion: v1
kind: Service
metadata:
  name: "omegared-nginx-svc"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    app.kubernetes.io/name: "omegared-nginx"
