name: Helm CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write    
  packages: write

env:
  # TODO  this env can be fix
  GITHUB_ACCOUNT_NAME: supanut741355
  GITHUB_REGISTRY_NAME: dev_space
  GITHUB_PAGE_URL: https://supanut741355.github.io/helm-charts-poc/

  # TODO this env should get value from Chart.yaml
  CHART_NAME: omegared
  CHART_VERSION: 0.4.0


jobs:
  helm_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.4

      - name: Pack Helm Chart
        run: |
          helm package ./omegared

      - name: debug
        run: |
          ls -l

      - name: upload helm package to artifact
        uses: actions/upload-artifact@v4
        with:
          name: $CHART_NAME-$CHART_VERSION.tgz
          path: ./


  helm_push:
    needs: helm_package
    runs-on: ubuntu-latest
    steps:
      - name: Authen GHCR
        env:
          HELM_CHART_GHCR_PAT_KEY: ${{ secrets.HELM_CHART_GHCR_PAT_KEY}}
        run: |
          echo $HELM_CHART_GHCR_PAT_KEY | docker login ghcr.io -u $GITHUB_ACCOUNT_NAME --password-stdin


      - name: Download helm package
        uses: actions/download-artifact@v4
        with:
          name: $CHART_NAME-$CHART_VERSION.tgz
          path: ./

      - name: debug
        run: |
          ls -l

      - name: helm_push
        run: |
          helm push $CHART_NAME-$CHART_VERSION.tgz oci://ghcr.io/$GITHUB_ACCOUNT_NAME/$GITHUB_REGISTRY_NAME

  helm_update_index:
    needs: helm_push
    runs-on: ubuntu-latest
    steps: 
      - name: check out gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Download helm package
        uses: actions/download-artifact@v4
        with:
          name: $CHART_NAME-$CHART_VERSION.tgz
          path: ./

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.4

      - name: Update Helm repo index
        run: |
          helm repo index . --url $GITHUB_PAGE_URL

      - name: Commit and Push index.yaml
        run: |
          git config user.name "supanut741355"
          git config user.email "supanut.wizard@gmail.com"
          git add index.yaml 
          git commit -m "Update Helm repo index"
          git push origin gh-pages


